# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyconfi2016', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_type', models.CharField(choices=[(b'individual_eb', b'Individual Early Bird'), (b'individual', b'Individual'), (b'corporate_eb', b'Corporate Early Bird'), (b'corporate', b'Corporate'), (b'student', b'Student'), (b'organizer', b'Organizer'), (b'speaker', b'Speaker'), (b'sponsor', b'Sponsor')], max_length=30)),
                ('country', models.CharField(max_length=2)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('dinner', models.BooleanField(default=True)),
                ('accommodation', models.BooleanField()),
                ('preconf', models.BooleanField()),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('billed', models.BooleanField(default=False)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('bill_text', models.TextField(blank=True, null=True)),
                ('notified_date', models.DateField(blank=True, null=True)),
                ('notify_text', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('registered_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
