# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyconfi2016', '0002_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='accommodation',
        ),
    ]
